defaults:
  - _self_
  - model: llava_qwen2_0_5b
  - quant: fp16
  - gen: default
  - preprocess: default
  - verbosity: default
  - hydra: default

csv: data/examples.csv
out_jsonl: outputs/run.jsonl   # legacy; still supported (will be written if set)
limit: null
