data:
  augmentation: null
  batch_size: 128
  dataset: MNIST
logger:
  entity: your_wandb_entity
  project: pytorch-lightning-uv
  run_name: test_CNN_Dropout_batchnorm
model:
  activation: relu
  dropout: 0.2
  n_channels_1: 32
  n_channels_2: 64
  n_fc_1: 128
  name: CNN
optimizer:
  lr: 0.0001
  name: adam
training:
  accumulate_grad_batches: null
  gradient_clip_val: null
  max_epochs: 25
  precision: null
