data:
  augmentation: null
  transform: efficientnetv2_pt
  batch_size: 64
  dataset: Fashion MNIST
logger:
  entity: your_wandb_entity
  project: pytorch-lightning-uv
  run_name: Efficientnet_V2_Fashion_MNIST
model:
  activation: relu
  dropout: 0.2
  efficient_version: s
  name: Efficientnet_V2
  unfreeze_layers:
    - "blocks"
    - "classifier"
optimizer:
  lr: 0.0001
  name: adam
training:
  accumulate_grad_batches: null
  gradient_clip_val: null
  max_epochs: 6
  precision: null
