# Minimal config for benchmarking LLaVA-OneVision
data:
  path: data/examples.csv          # CSV with image_paths,prompt,answer (answer optional)
  multi_image: false               # set true to test multi-image

model:
  model_id: llava-hf/llava-onevision-qwen2-0.5b-ov-hf  # use *ov* for multi-image/video
  dtype: fp16                       # fp32|fp16|bf16
  quantization: none                # none|bnb-int8|bnb-int4
  bnb_4bit_compute_dtype: bf16
  max_new_tokens: 64
  temperature: 0.0
  top_p: 1.0
  pad_token_left: true              # recommended for batched gen

runtime:
  runs: 5
  warmup_runs: 1
