data:
  augmentation: null
  transform: resnet_pt
  batch_size: 128
  dataset: Fashion MNIST
logger:
  entity: your_wandb_entity
  project: pytorch-lightning-uv
  run_name: resnet18_Fashion_MNIST
model:
  name: resnet18
  unfreeze_layers:
    - layer1
    - layer2
    - layer3
    - layer4
    - fc

optimizer:
  lr: 0.0001
  name: adam
training:
  accumulate_grad_batches: null
  gradient_clip_val: null
  max_epochs: 6
  precision: null
