data:
  augmentation: null
  batch_size: 128
  dataset: MNIST
logger:
  entity: your_wandb_entity
  project: pytorch-lightning-uv
  run_name: MNIST_MLP
model:
  activation: relu
  dropout: null
  n_layer_1: 512
  n_layer_2: 128
  name: MLP
optimizer:
  lr: 0.0001
  name: adam
training:
  accumulate_grad_batches: null
  gradient_clip_val: null
  max_epochs: 24
  precision: null
